const FETCH_POST = 'FETCH_POST';
const FETCH_POSTS = 'FETCH_POSTS';
const DELETE_POSTS = 'DELETE_POSTS';
const EDIT_POSTS= 'EDIT_POSTS';

export const ACTION_TYPES = {
    FETCH_POST,
    FETCH_POSTS,
    DELETE_POSTS,
    EDIT_POSTS,
}