const FETCH_POST = 'FETCH_POST';
const FETCH_POSTS = 'FETCH_POSTS';
const DELETE_POST = 'DELETE_POST';
const EDIT_POST= 'EDIT_POST';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const CREATE_POST = 'CREATE_POST';

export const ACTION_TYPES = {
    FETCH_POST,
    FETCH_POSTS,
    DELETE_POST,
    EDIT_POST,
    SIGN_IN,
    SIGN_OUT,
    CREATE_POST
}
